# Generated by Django 3.1.2 on 2020-10-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
