# Generated by Django 3.1.2 on 2020-10-24 12:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('todoer', '0001_initial'), ('todoer', '0002_auto_20200908_1829'), ('todoer', '0003_auto_20200908_1959'), ('todoer', '0004_auto_20200908_2016'), ('todoer', '0005_task_template'), ('todoer', '0006_tasktemplate_active'), ('todoer', '0007_auto_20201024_0528')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255)),
                ('morning', models.BooleanField()),
                ('reminder_time', models.CharField(blank=True, default='', help_text='like 9pm', max_length=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoer.schedule')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('order', models.IntegerField()),
                ('todoist_id', models.BigIntegerField()),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoer.tasktemplate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
    ]
