# Generated by Django 3.1.1 on 2020-09-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='reminder_time',
            field=models.CharField(blank=True, default='', help_text='like 9pm', max_length=10),
        ),
    ]
