# Generated by Django 3.1.2 on 2020-10-24 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoer', '0001_squashed_0002_auto_20201024_0544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTemplate',
            new_name='Habit',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='template',
            new_name='habit',
        ),
    ]
