# Generated by Django 3.1.1 on 2020-09-09 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0002_auto_20200908_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todoist_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
