# Generated by Django 3.1.1 on 2020-09-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0003_auto_20200908_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todoist_id',
            field=models.BigIntegerField(),
        ),
    ]
