# Generated by Django 3.1.1 on 2020-09-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0004_auto_20200908_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoer.tasktemplate'),
        ),
    ]
