# Generated by Django 3.1.1 on 2020-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0005_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
