# Generated by Django 3.1.2 on 2020-10-26 01:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20201024_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
