# Generated by Django 3.1.2 on 2020-10-26 01:42

from django.db import migrations


def combine_names(apps, schema_editor):
    Habit = apps.get_model('habits', 'Habit')
    for habit in Habit.objects.all():
        habit.days = habit.schedule.days
        habit.save()


class Migration(migrations.Migration):
    dependencies = [
        ('habits', '0003_habit_days'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
