# Generated by Django 3.1.2 on 2020-10-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20201026_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
