# Generated by Django 3.1.2 on 2020-11-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20201102_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='streaks_and_goals',
            new_name='show_streaks',
        ),
    ]
