# Generated by Django 3.1.2 on 2020-11-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20201102_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='show_streaks',
            new_name='streaks',
        ),
    ]
